Repository neeruram1/Crate, pull requests merged in 2020-10, with the labels that each got.

#43 Feature/survey body
  code/api/.env
  code/api/.gitignore
  code/api/src/config/env.js
  code/api/src/config/server.json
  code/web/.env
  code/web/src/modules/styleSurvey/CategoryImage.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/category.js
  code/web/src/modules/survey/List.js
Labels: Front End, enhancement, new feature

#44 Feature/js survey styling
  code/web/package-lock.json
  code/web/src/modules/styleSurvey/CategoryImage.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/category.js
  code/web/src/setup/client/App.js
Labels: Front End

#48 Feature/js add survey images to state
  code/web/src/modules/crate/List.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/api/state.js
  code/web/src/modules/survey/List.js
  code/web/src/setup/store.js
Labels: Front End, enhancement

#52 Feature/js survey images fetch
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/api/state.js
Labels: Front End, enhancement

#53 Feature/js submit survey button
  code/web/src/modules/crate/Item.js
  code/web/src/modules/styleSurvey/Survey.js
Labels: Front End, enhancement

#54 Feature/display survey items
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/styleSurvey/CategoryImage.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/api/state.js
  code/web/src/modules/styleSurvey/category.js
  code/web/src/setup/store.js
Labels: Front End

#59 Feature/survey results
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/styleSurvey/CategoryImage.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/State.spec.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/category.js
  code/web/src/modules/user/api/actions.js
Labels: Front End

#60 Feature/post style
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/State.spec.js
  code/web/src/modules/styleSurvey/api/actions.js
Labels: Front End

#62 Add response variable, create and pass 2 more tests #26
  code/web/src/modules/styleSurvey/api/State.spec.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/api/state.js
Labels: Front End

#63 Feature/js post survey result
  code/web/src/modules/styleSurvey/CategoryImage.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/api/state.js
  code/web/src/modules/styleSurvey/category.js
Labels: Front End, enhancement

#66 Cleanup
  code/web/src/modules/styleSurvey/CategoryImage.js
  code/web/src/modules/styleSurvey/Survey.js
  code/web/src/modules/styleSurvey/api/actions.js
  code/web/src/modules/styleSurvey/category.js
Labels: Front End
